/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.scoping2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.scoping2.scoping2.Chapter#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.scoping2.scoping2.Chapter#getParagraphs <em>Paragraphs</em>}</li>
 *   <li>{@link org.xtext.example.scoping2.scoping2.Chapter#getReferences <em>References</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getChapter()
 * @model
 * @generated
 */
public interface Chapter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getChapter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping2.scoping2.Chapter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Paragraphs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping2.scoping2.Paragraph}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragraphs</em>' containment reference list.
   * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getChapter_Paragraphs()
   * @model containment="true"
   * @generated
   */
  EList<Paragraph> getParagraphs();

  /**
   * Returns the value of the '<em><b>References</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping2.scoping2.Reference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>References</em>' containment reference list.
   * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getChapter_References()
   * @model containment="true"
   * @generated
   */
  EList<Reference> getReferences();

} // Chapter
