/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.scoping2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.scoping2.scoping2.Reference#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getReference()
 * @model
 * @generated
 */
public interface Reference extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Chapter)
   * @see org.xtext.example.scoping2.scoping2.Scoping2Package#getReference_Ref()
   * @model
   * @generated
   */
  Chapter getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping2.scoping2.Reference#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Chapter value);

} // Reference
