/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.scoping2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.scoping2.scoping2.Scoping2Factory
 * @model kind="package"
 * @generated
 */
public interface Scoping2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "scoping2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/scoping2/Scoping2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "scoping2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Scoping2Package eINSTANCE = org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.scoping2.scoping2.impl.BookImpl <em>Book</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.scoping2.scoping2.impl.BookImpl
   * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getBook()
   * @generated
   */
  int BOOK = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Chapters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__CHAPTERS = 2;

  /**
   * The number of structural features of the '<em>Book</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.scoping2.scoping2.impl.DImportImpl <em>DImport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.scoping2.scoping2.impl.DImportImpl
   * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getDImport()
   * @generated
   */
  int DIMPORT = 1;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>DImport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.scoping2.scoping2.impl.ChapterImpl <em>Chapter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.scoping2.scoping2.impl.ChapterImpl
   * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getChapter()
   * @generated
   */
  int CHAPTER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Paragraphs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPTER__PARAGRAPHS = 1;

  /**
   * The feature id for the '<em><b>References</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPTER__REFERENCES = 2;

  /**
   * The number of structural features of the '<em>Chapter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAPTER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.scoping2.scoping2.impl.ParagraphImpl <em>Paragraph</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.scoping2.scoping2.impl.ParagraphImpl
   * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getParagraph()
   * @generated
   */
  int PARAGRAPH = 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH__TEXT = 0;

  /**
   * The number of structural features of the '<em>Paragraph</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.scoping2.scoping2.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.scoping2.scoping2.impl.ReferenceImpl
   * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__REF = 0;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.scoping2.scoping2.Book <em>Book</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Book</em>'.
   * @see org.xtext.example.scoping2.scoping2.Book
   * @generated
   */
  EClass getBook();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.scoping2.scoping2.Book#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.scoping2.scoping2.Book#getName()
   * @see #getBook()
   * @generated
   */
  EAttribute getBook_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.scoping2.scoping2.Book#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.example.scoping2.scoping2.Book#getImports()
   * @see #getBook()
   * @generated
   */
  EReference getBook_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.scoping2.scoping2.Book#getChapters <em>Chapters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chapters</em>'.
   * @see org.xtext.example.scoping2.scoping2.Book#getChapters()
   * @see #getBook()
   * @generated
   */
  EReference getBook_Chapters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.scoping2.scoping2.DImport <em>DImport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DImport</em>'.
   * @see org.xtext.example.scoping2.scoping2.DImport
   * @generated
   */
  EClass getDImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.scoping2.scoping2.DImport#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.xtext.example.scoping2.scoping2.DImport#getImportedNamespace()
   * @see #getDImport()
   * @generated
   */
  EAttribute getDImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.xtext.example.scoping2.scoping2.Chapter <em>Chapter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chapter</em>'.
   * @see org.xtext.example.scoping2.scoping2.Chapter
   * @generated
   */
  EClass getChapter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.scoping2.scoping2.Chapter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.scoping2.scoping2.Chapter#getName()
   * @see #getChapter()
   * @generated
   */
  EAttribute getChapter_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.scoping2.scoping2.Chapter#getParagraphs <em>Paragraphs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragraphs</em>'.
   * @see org.xtext.example.scoping2.scoping2.Chapter#getParagraphs()
   * @see #getChapter()
   * @generated
   */
  EReference getChapter_Paragraphs();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.scoping2.scoping2.Chapter#getReferences <em>References</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>References</em>'.
   * @see org.xtext.example.scoping2.scoping2.Chapter#getReferences()
   * @see #getChapter()
   * @generated
   */
  EReference getChapter_References();

  /**
   * Returns the meta object for class '{@link org.xtext.example.scoping2.scoping2.Paragraph <em>Paragraph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragraph</em>'.
   * @see org.xtext.example.scoping2.scoping2.Paragraph
   * @generated
   */
  EClass getParagraph();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.scoping2.scoping2.Paragraph#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.scoping2.scoping2.Paragraph#getText()
   * @see #getParagraph()
   * @generated
   */
  EAttribute getParagraph_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.scoping2.scoping2.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.xtext.example.scoping2.scoping2.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.scoping2.scoping2.Reference#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.example.scoping2.scoping2.Reference#getRef()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Ref();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Scoping2Factory getScoping2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.scoping2.scoping2.impl.BookImpl <em>Book</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.scoping2.scoping2.impl.BookImpl
     * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getBook()
     * @generated
     */
    EClass BOOK = eINSTANCE.getBook();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOK__NAME = eINSTANCE.getBook_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOK__IMPORTS = eINSTANCE.getBook_Imports();

    /**
     * The meta object literal for the '<em><b>Chapters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOK__CHAPTERS = eINSTANCE.getBook_Chapters();

    /**
     * The meta object literal for the '{@link org.xtext.example.scoping2.scoping2.impl.DImportImpl <em>DImport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.scoping2.scoping2.impl.DImportImpl
     * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getDImport()
     * @generated
     */
    EClass DIMPORT = eINSTANCE.getDImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIMPORT__IMPORTED_NAMESPACE = eINSTANCE.getDImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.xtext.example.scoping2.scoping2.impl.ChapterImpl <em>Chapter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.scoping2.scoping2.impl.ChapterImpl
     * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getChapter()
     * @generated
     */
    EClass CHAPTER = eINSTANCE.getChapter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAPTER__NAME = eINSTANCE.getChapter_Name();

    /**
     * The meta object literal for the '<em><b>Paragraphs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAPTER__PARAGRAPHS = eINSTANCE.getChapter_Paragraphs();

    /**
     * The meta object literal for the '<em><b>References</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAPTER__REFERENCES = eINSTANCE.getChapter_References();

    /**
     * The meta object literal for the '{@link org.xtext.example.scoping2.scoping2.impl.ParagraphImpl <em>Paragraph</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.scoping2.scoping2.impl.ParagraphImpl
     * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getParagraph()
     * @generated
     */
    EClass PARAGRAPH = eINSTANCE.getParagraph();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAGRAPH__TEXT = eINSTANCE.getParagraph_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.scoping2.scoping2.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.scoping2.scoping2.impl.ReferenceImpl
     * @see org.xtext.example.scoping2.scoping2.impl.Scoping2PackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__REF = eINSTANCE.getReference_Ref();

  }

} //Scoping2Package
