/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.scoping2.ui.internal.Scoping2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Scoping2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Scoping2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Scoping2Activator activator = Scoping2Activator.getInstance();
		return activator != null ? activator.getInjector(Scoping2Activator.ORG_XTEXT_EXAMPLE_SCOPING2_SCOPING2) : null;
	}

}
