/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.scoping2.ui.AbstractScoping2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Scoping2UiModule extends AbstractScoping2UiModule {
  public Scoping2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
