/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.scoping2.parser.antlr.internal.InternalScoping2Parser;
import org.xtext.example.scoping2.services.Scoping2GrammarAccess;

public class Scoping2Parser extends AbstractAntlrParser {

	@Inject
	private Scoping2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalScoping2Parser createParser(XtextTokenStream stream) {
		return new InternalScoping2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Book";
	}

	public Scoping2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Scoping2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
