/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Scoping2AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/scoping2/parser/antlr/internal/InternalScoping2.tokens");
	}
}
