/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.validation;

import org.xtext.example.scoping2.validation.AbstractScoping2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Scoping2Validator extends AbstractScoping2Validator {
}
