/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.ui.contentassist;

import org.xtext.example.scoping2.ui.contentassist.AbstractScoping2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Scoping2ProposalProvider extends AbstractScoping2ProposalProvider {
}
