/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractScoping2ScopeProvider extends DelegatingScopeProvider {
}
