/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.ide;

import org.xtext.example.scoping2.ide.AbstractScoping2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Scoping2IdeModule extends AbstractScoping2IdeModule {
}
