/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.scoping2.Scoping2RuntimeModule;
import org.xtext.example.scoping2.Scoping2StandaloneSetup;
import org.xtext.example.scoping2.ide.Scoping2IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Scoping2IdeSetup extends Scoping2StandaloneSetup {
  @Override
  public Injector createInjector() {
    Scoping2RuntimeModule _scoping2RuntimeModule = new Scoping2RuntimeModule();
    Scoping2IdeModule _scoping2IdeModule = new Scoping2IdeModule();
    return Guice.createInjector(Modules2.mixin(_scoping2RuntimeModule, _scoping2IdeModule));
  }
}
