/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Scoping2StandaloneSetup extends Scoping2StandaloneSetupGenerated {

	def static void doSetup() {
		new Scoping2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
