/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.scoping2;

import org.xtext.example.scoping2.Scoping2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Scoping2StandaloneSetup extends Scoping2StandaloneSetupGenerated {
  public static void doSetup() {
    new Scoping2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
